// NagiosQL — Go backend for managing Nagios Core configuration.
//
//	@title                      NagiosQL API
//	@version                    1.0
//	@description                REST API for managing Nagios Core monitoring configuration.
//	@host                       localhost:8081
//	@BasePath                   /api/v1
//	@securityDefinitions.apikey BearerAuth
//	@in                         header
//	@name                       Authorization
//
// Build-time variables injected via -ldflags:
//
//	-X main.Version=v1.0.0
//	-X main.BuildDate=2026-06-17T00:00:00Z
package main

import (
	"embed"

	"github.com/jniltinho/go-nagiosql/cmd"
	_ "github.com/jniltinho/go-nagiosql/docs" // generated by swag init; registers swagger info
)

//go:embed docs
var swaggerDocs embed.FS

// Version, BuildDate are set at build time via -ldflags.
var (
	Version   = "dev"
	BuildDate = "unknown"
)

func main() {
	cmd.SetBuildInfo(Version, BuildDate)
	cmd.DocsFS = swaggerDocs
	cmd.Execute()
}
