# ── Nagios Core (porta 80) ────────────────────────────────────────────────────
server {
    listen      80;
    server_name _;
    root        /usr/local/nagios/share;

    auth_basic           "Nagios Auth";
    auth_basic_user_file /usr/local/nagios/etc/htpasswd.users;

    index index.php index.html;

    rewrite ^/nagios/(.*) /$1;

    location = / {
        return 302 $scheme://$http_host/cgi-bin/tac.cgi;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        try_files     $uri =404;
        fastcgi_pass  unix:/run/php/php8.4-fpm.sock;
        fastcgi_index index.php;
        include       fastcgi.conf;
    }

    location ~ \.cgi$ {
        fastcgi_param AUTH_USER   $remote_user;
        fastcgi_param REMOTE_USER $remote_user;
        include       fastcgi.conf;
        fastcgi_pass  127.0.0.1:9000;
    }
}

# ── NagiosQL (porta 8081) ─────────────────────────────────────────────────────
server {
    listen      8081;
    server_name _;
    root        /var/www/nagiosql;
    index       index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files     $uri =404;
        fastcgi_pass  unix:/run/php/php8.4-fpm.sock;
        fastcgi_index index.php;
        include       fastcgi.conf;
    }

    location ~ /\. {
        deny all;
    }
}
