// Package nagconfig generates Nagios .cfg files from the database,
// matching the output format of the PHP NagiosQL application.
package nagconfig

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"go-nagiosql/internal/buildinfo"
	"go-nagiosql/internal/models"
	"gorm.io/gorm"
)

// Generator writes Nagios configuration files from the database.
type Generator struct {
	db         *gorm.DB
	hostDir    string
	serviceDir string
	backupDir  string
	appVersion string
}

// New creates a Generator using explicit directory paths.
// appVersion is the Go binary version injected at build time (e.g. "v1.2.3").
func New(db *gorm.DB, hostDir, serviceDir, backupDir, appVersion string) *Generator {
	if appVersion == "" {
		appVersion = buildinfo.Version
	}
	return &Generator{
		db:         db,
		hostDir:    hostDir,
		serviceDir: serviceDir,
		backupDir:  backupDir,
		appVersion: appVersion,
	}
}

// fileHeader returns the standard PHP NagiosQL file header for the given description.
func (g *Generator) fileHeader(description string) string {
	sep := "###############################################################################"
	return sep + "\n" +
		"#\n" +
		"# " + description + "\n" +
		"#\n" +
		"# Created by: Go-NagiosQL Version " + g.appVersion + "\n" +
		"# Date:\t      " + time.Now().Format("2006-01-02 15:04:05") + "\n" +
		"# Version:    Nagios 4.x config file\n" +
		"#\n" +
		"# --- DO NOT EDIT THIS FILE BY HAND --- \n" +
		"# Nagios QL will overwite all manual settings during the next update\n" +
		"#\n" +
		sep + "\n" +
		"\n"
}

// fileFooter returns the standard PHP NagiosQL file footer for the given description.
func (g *Generator) fileFooter(description string) string {
	sep := "###############################################################################"
	return sep + "\n" +
		"#\n" +
		"# " + description + "\n" +
		"#\n" +
		"# END OF FILE\n" +
		"#\n" +
		sep + "\n"
}

// wrapFile prepends the header and appends the footer to the given content.
func (g *Generator) wrapFile(description string, content []byte) []byte {
	var b bytes.Buffer
	b.WriteString(g.fileHeader(description))
	b.Write(content)
	b.WriteString(g.fileFooter(description))
	return b.Bytes()
}

// WriteHost renders and writes a single host .cfg file.
func (g *Generator) WriteHost(hostID uint) error {
	var host models.Host
	if err := g.db.First(&host, hostID).Error; err != nil {
		return fmt.Errorf("host %d not found: %w", hostID, err)
	}
	content, err := g.renderHost(&host)
	if err != nil {
		return err
	}
	filename := sanitizeName(host.HostName) + ".cfg"
	return g.writeWithBackup(filepath.Join(g.hostDir, filename),
		g.wrapFile("Host configuration file", content))
}

// WriteServiceGroup writes one .cfg file containing all services with the given config_name.
func (g *Generator) WriteServiceGroup(configName string) error {
	var svcs []models.Service
	if err := g.db.Where("config_name = ? AND active = '1'", configName).
		Order("service_description").Find(&svcs).Error; err != nil {
		return fmt.Errorf("loading services %q: %w", configName, err)
	}
	if len(svcs) == 0 {
		return nil
	}
	var buf bytes.Buffer
	for _, svc := range svcs {
		chunk, err := g.renderService(&svc)
		if err != nil {
			return err
		}
		buf.Write(chunk)
		buf.WriteByte('\n')
	}
	filename := sanitizeName(configName) + ".cfg"
	return g.writeWithBackup(filepath.Join(g.serviceDir, filename),
		g.wrapFile("Service configuration file", buf.Bytes()))
}

// WriteAllHosts writes a .cfg file for every active host.
func (g *Generator) WriteAllHosts() (int, error) {
	var hosts []models.Host
	if err := g.db.Where("active = '1'").Find(&hosts).Error; err != nil {
		return 0, err
	}
	var written int
	for _, h := range hosts {
		if err := g.WriteHost(h.ID); err != nil {
			return written, err
		}
		written++
	}
	return written, nil
}

// WriteAllServices writes one .cfg file per distinct config_name.
func (g *Generator) WriteAllServices() (int, error) {
	var names []string
	g.db.Model(&models.Service{}).Distinct("config_name").Where("active = '1'").Pluck("config_name", &names)
	var written int
	for _, name := range names {
		if err := g.WriteServiceGroup(name); err != nil {
			return written, err
		}
		written++
	}
	return written, nil
}

// WriteAll writes all object types and returns total files written.
func (g *Generator) WriteAll() (int, error) {
	base := filepath.Dir(strings.TrimRight(g.hostDir, "/"))

	singles := []struct {
		name string
		fn   func(string) error
	}{
		{"commands.cfg", g.WriteCommands},
		{"contactgroups.cfg", g.WriteContactGroups},
		{"contacts.cfg", g.WriteContacts},
		{"contacttemplates.cfg", g.WriteContactTemplates},
		{"hostgroups.cfg", g.WriteHostGroups},
		{"hosttemplates.cfg", g.WriteHostTemplates},
		{"hostdependencies.cfg", g.WriteHostDependencies},
		{"hostescalations.cfg", g.WriteHostEscalations},
		{"hostextinfo.cfg", g.WriteHostExtInfo},
		{"servicetemplates.cfg", g.WriteServiceTemplates},
		{"servicegroups.cfg", g.WriteServiceGroups},
		{"servicedependencies.cfg", g.WriteServiceDependencies},
		{"serviceescalations.cfg", g.WriteServiceEscalations},
		{"serviceextinfo.cfg", g.WriteServiceExtInfo},
		{"timeperiods.cfg", g.WriteTimeperiods},
	}

	total := 0
	h, err := g.WriteAllHosts()
	if err != nil {
		return total, err
	}
	total += h

	s, err := g.WriteAllServices()
	if err != nil {
		return total, err
	}
	total += s

	for _, item := range singles {
		if err := item.fn(filepath.Join(base, item.name)); err != nil {
			return total, fmt.Errorf("%s: %w", item.name, err)
		}
		total++
	}
	return total, nil
}

// WriteCommands writes all active commands to a single commands.cfg file,
// matching the PHP NagiosQL output format (tab-indented, key padded to 31 chars).
func (g *Generator) WriteCommands(outputFile string) error {
	var cmds []models.Command
	if err := g.db.Where("active = '1'").Order("command_name").Find(&cmds).Error; err != nil {
		return fmt.Errorf("loading commands: %w", err)
	}
	var buf bytes.Buffer
	for _, cmd := range cmds {
		buf.WriteString("define command {\n")
		buf.WriteString(cmdField("command_name", cmd.CommandName))
		buf.WriteString(cmdField("command_line", bangDecode(cmd.CommandLine)))
		// register=1 is always written for commands (PHP NagiosQL behavior).
		buf.WriteString(cmdField("register", cmd.Register))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Check command configuration file", buf.Bytes()))
}

// WriteContactGroups writes contactgroups.cfg.
func (g *Generator) WriteContactGroups(outputFile string) error {
	var rows []models.Contactgroup
	if err := g.db.Where("active = '1'").Order("contactgroup_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, cg := range rows {
		buf.WriteString("define contactgroup {\n")
		buf.WriteString(cmdField("contactgroup_name", cg.ContactgroupName))
		buf.WriteString(cmdField("alias", cg.Alias))
		if members := g.resolveContactgroupMembers(cg.ID); members != "" {
			buf.WriteString(cmdField("members", members))
		}
		buf.WriteString(cmdField("register", cg.Register))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Contact group configuration file", buf.Bytes()))
}

// WriteContacts writes contacts.cfg.
func (g *Generator) WriteContacts(outputFile string) error {
	var rows []models.Contact
	if err := g.db.Where("active = '1'").Order("contact_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, c := range rows {
		buf.WriteString("define contact {\n")
		buf.WriteString(cmdField("contact_name", c.ContactName))
		buf.WriteString(cmdField("alias", c.Alias))
		if c.Email != "" {
			buf.WriteString(cmdField("email", c.Email))
		}
		if tpl := g.resolveContactTemplate(c.ID); tpl != "" {
			buf.WriteString(cmdField("use", tpl))
		}
		buf.WriteString(cmdField("register", c.Register))
		buf.WriteString("\t}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Contact configuration file", buf.Bytes()))
}

// WriteContactTemplates writes contacttemplates.cfg.
func (g *Generator) WriteContactTemplates(outputFile string) error {
	var rows []models.Contacttemplate
	if err := g.db.Where("active = '1'").Order("template_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, ct := range rows {
		buf.WriteString("define contact {\n")
		buf.WriteString(cmdField("name", ct.TemplateName))
		if period := g.resolveTimeperiodName(ct.HostNotificationPeriod); period != "" {
			buf.WriteString(cmdField("host_notification_period", period))
		}
		if period := g.resolveTimeperiodName(ct.ServiceNotificationPeriod); period != "" {
			buf.WriteString(cmdField("service_notification_period", period))
		}
		if ct.HostNotificationOptions != "" {
			buf.WriteString(cmdField("host_notification_options", ct.HostNotificationOptions))
		}
		if ct.ServiceNotificationOptions != "" {
			buf.WriteString(cmdField("service_notification_options", ct.ServiceNotificationOptions))
		}
		if cmd := g.resolveContactTemplateHostCmd(ct.ID); cmd != "" {
			buf.WriteString(cmdField("host_notification_commands", cmd))
		}
		if cmd := g.resolveContactTemplateSvcCmd(ct.ID); cmd != "" {
			buf.WriteString(cmdField("service_notification_commands", cmd))
		}
		buf.WriteString(cmdField("register", "0"))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Contact template configuration file", buf.Bytes()))
}

// WriteHostGroups writes hostgroups.cfg.
func (g *Generator) WriteHostGroups(outputFile string) error {
	var rows []models.Hostgroup
	if err := g.db.Where("active = '1'").Order("hostgroup_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, hg := range rows {
		buf.WriteString("define hostgroup {\n")
		buf.WriteString(cmdField("hostgroup_name", hg.HostgroupName))
		buf.WriteString(cmdField("alias", hg.Alias))
		if members := g.resolveHostgroupMembers(hg.ID); members != "" {
			buf.WriteString(cmdField("members", members))
		}
		buf.WriteString(cmdField("register", hg.Register))
		buf.WriteString("}\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Host group configuration file", buf.Bytes()))
}

// WriteHostTemplates writes hosttemplates.cfg.
func (g *Generator) WriteHostTemplates(outputFile string) error {
	var rows []models.Hosttemplate
	if err := g.db.Where("active = '1'").Order("template_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, ht := range rows {
		buf.WriteString("define host {\n")
		// Fields follow the DB column order of tbl_hosttemplate (PHP uses SELECT *).
		buf.WriteString(cmdField("name", ht.TemplateName))
		if ht.Hostgroups != 0 {
			if hg := g.resolveHostTemplateHostgroups(ht.ID); hg != "" {
				buf.WriteString(cmdField("hostgroups", hg))
			}
		}
		if cc := g.resolveCommandIDStr(ht.CheckCommand); cc != "" {
			buf.WriteString(cmdField("check_command", cc))
		}
		if tpl := g.resolveHostTemplateParent(ht.ID); tpl != "" {
			buf.WriteString(cmdField("use", tpl))
		}
		if ht.MaxCheckAttempts != nil {
			buf.WriteString(cmdField("max_check_attempts", fmt.Sprint(*ht.MaxCheckAttempts)))
		}
		if ht.CheckInterval != nil {
			buf.WriteString(cmdField("check_interval", fmt.Sprint(*ht.CheckInterval)))
		}
		if ht.RetryInterval != nil {
			buf.WriteString(cmdField("retry_interval", fmt.Sprint(*ht.RetryInterval)))
		}
		if ht.ActiveChecksEnabled != 2 {
			buf.WriteString(cmdField("active_checks_enabled", fmt.Sprint(ht.ActiveChecksEnabled)))
		}
		if ht.PassiveChecksEnabled != 2 {
			buf.WriteString(cmdField("passive_checks_enabled", fmt.Sprint(ht.PassiveChecksEnabled)))
		}
		if p := g.resolveTimeperiodName(ht.CheckPeriod); p != "" {
			buf.WriteString(cmdField("check_period", p))
		}
		if ht.ObsessOverHost != 2 {
			buf.WriteString(cmdField("obsess_over_host", fmt.Sprint(ht.ObsessOverHost)))
		}
		if ht.CheckFreshness != 2 {
			buf.WriteString(cmdField("check_freshness", fmt.Sprint(ht.CheckFreshness)))
		}
		if ht.EventHandlerEnabled != 2 {
			buf.WriteString(cmdField("event_handler_enabled", fmt.Sprint(ht.EventHandlerEnabled)))
		}
		if ht.FlapDetectionEnabled != 2 {
			buf.WriteString(cmdField("flap_detection_enabled", fmt.Sprint(ht.FlapDetectionEnabled)))
		}
		if ht.ProcessPerfData != 2 {
			buf.WriteString(cmdField("process_perf_data", fmt.Sprint(ht.ProcessPerfData)))
		}
		if ht.RetainStatusInfo != 2 {
			buf.WriteString(cmdField("retain_status_information", fmt.Sprint(ht.RetainStatusInfo)))
		}
		if ht.RetainNonstatusInfo != 2 {
			buf.WriteString(cmdField("retain_nonstatus_information", fmt.Sprint(ht.RetainNonstatusInfo)))
		}
		if ht.ContactGroups != 0 {
			if cg := g.resolveHostTemplateContactGroups(ht.ID); cg != "" {
				buf.WriteString(cmdField("contact_groups", cg))
			}
		}
		if ht.NotificationInterval != nil {
			buf.WriteString(cmdField("notification_interval", fmt.Sprint(*ht.NotificationInterval)))
		}
		if p := g.resolveTimeperiodName(ht.NotificationPeriod); p != "" {
			buf.WriteString(cmdField("notification_period", p))
		}
		if ht.NotificationOptions != "" {
			buf.WriteString(cmdField("notification_options", ht.NotificationOptions))
		}
		if ht.NotificationsEnabled != 2 {
			buf.WriteString(cmdField("notifications_enabled", fmt.Sprint(ht.NotificationsEnabled)))
		}
		buf.WriteString(cmdField("register", "0"))
		buf.WriteString("}\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Host template configuration file", buf.Bytes()))
}

// WriteServiceTemplates writes servicetemplates.cfg.
func (g *Generator) WriteServiceTemplates(outputFile string) error {
	var rows []models.Servicetemplate
	if err := g.db.Where("active = '1'").Order("template_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, st := range rows {
		buf.WriteString("define service {\n")
		buf.WriteString(cmdField("name", st.TemplateName))
		if tpl := g.resolveServiceTemplateParent(st.ID); tpl != "" {
			buf.WriteString(cmdField("use", tpl))
		}
		if st.IsVolatile != 2 {
			buf.WriteString(cmdField("is_volatile", fmt.Sprint(st.IsVolatile)))
		}
		if st.MaxCheckAttempts != nil {
			buf.WriteString(cmdField("max_check_attempts", fmt.Sprint(*st.MaxCheckAttempts)))
		}
		if st.CheckInterval != nil {
			buf.WriteString(cmdField("check_interval", fmt.Sprint(*st.CheckInterval)))
		}
		if st.RetryInterval != nil {
			buf.WriteString(cmdField("retry_interval", fmt.Sprint(*st.RetryInterval)))
		}
		if st.ActiveChecksEnabled != 2 {
			buf.WriteString(cmdField("active_checks_enabled", fmt.Sprint(st.ActiveChecksEnabled)))
		}
		if st.PassiveChecksEnabled != 2 {
			buf.WriteString(cmdField("passive_checks_enabled", fmt.Sprint(st.PassiveChecksEnabled)))
		}
		if p := g.resolveTimeperiodName(st.CheckPeriod); p != "" {
			buf.WriteString(cmdField("check_period", p))
		}
		if st.ParallelizeCheck != 2 {
			buf.WriteString(cmdField("parallelize_check", fmt.Sprint(st.ParallelizeCheck)))
		}
		if st.ObsessOverService != 2 {
			buf.WriteString(cmdField("obsess_over_service", fmt.Sprint(st.ObsessOverService)))
		}
		if st.CheckFreshness != 2 {
			buf.WriteString(cmdField("check_freshness", fmt.Sprint(st.CheckFreshness)))
		}
		if st.EventHandlerEnabled != 2 {
			buf.WriteString(cmdField("event_handler_enabled", fmt.Sprint(st.EventHandlerEnabled)))
		}
		if st.FlapDetectionEnabled != 2 {
			buf.WriteString(cmdField("flap_detection_enabled", fmt.Sprint(st.FlapDetectionEnabled)))
		}
		if st.ProcessPerfData != 2 {
			buf.WriteString(cmdField("process_perf_data", fmt.Sprint(st.ProcessPerfData)))
		}
		if st.RetainStatusInfo != 2 {
			buf.WriteString(cmdField("retain_status_information", fmt.Sprint(st.RetainStatusInfo)))
		}
		if st.RetainNonstatusInfo != 2 {
			buf.WriteString(cmdField("retain_nonstatus_information", fmt.Sprint(st.RetainNonstatusInfo)))
		}
		if st.NotificationInterval != nil {
			buf.WriteString(cmdField("notification_interval", fmt.Sprint(*st.NotificationInterval)))
		}
		if p := g.resolveTimeperiodName(st.NotificationPeriod); p != "" {
			buf.WriteString(cmdField("notification_period", p))
		}
		if st.NotificationOptions != "" {
			buf.WriteString(cmdField("notification_options", st.NotificationOptions))
		}
		if st.NotificationsEnabled != 2 {
			buf.WriteString(cmdField("notifications_enabled", fmt.Sprint(st.NotificationsEnabled)))
		}
		if st.ContactGroups != 0 {
			if cg := g.resolveServiceTemplateContactGroups(st.ID); cg != "" {
				buf.WriteString(cmdField("contact_groups", cg))
			}
		}
		buf.WriteString(cmdField("register", "0"))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Service template configuration file", buf.Bytes()))
}

// WriteTimeperiods writes timeperiods.cfg.
func (g *Generator) WriteTimeperiods(outputFile string) error {
	var rows []models.Timeperiod
	if err := g.db.Where("active = '1'").Order("timeperiod_name").Find(&rows).Error; err != nil {
		return err
	}
	var buf bytes.Buffer
	for _, tp := range rows {
		buf.WriteString("define timeperiod {\n")
		buf.WriteString(cmdField("timeperiod_name", tp.TimeperiodName))
		buf.WriteString(cmdField("alias", tp.Alias))
		if tp.Name != "" {
			buf.WriteString(cmdField("name", tp.Name))
		}
		if tp.UseTemplate != 0 {
			if used := g.resolveTimeperiodUse(tp.ID); used != "" {
				buf.WriteString(cmdField("use", used))
			}
		}
		buf.WriteString(cmdField("register", tp.Register))
		// Day/date ranges from tbl_timedefinition, ordered by insertion ID (matches PHP output).
		ranges := g.resolveTimedefinitions(tp.ID)
		for _, r := range ranges {
			buf.WriteString(cmdField(r[0], r[1]))
		}
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Time period configuration file", buf.Bytes()))
}

// --- Rendering ---

func (g *Generator) renderHost(h *models.Host) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("define host {\n")

	// Fields follow DB column order of tbl_host (PHP uses SELECT * → foreach).
	buf.WriteString(cmdField("host_name", h.HostName))
	buf.WriteString(cmdField("alias", h.Alias))
	if h.DisplayName != "" {
		buf.WriteString(cmdField("display_name", h.DisplayName))
	}
	buf.WriteString(cmdField("address", h.Address))
	if h.Hostgroups != 0 {
		if hg := g.resolveHostHostgroups(h.ID); hg != "" {
			buf.WriteString(cmdField("hostgroups", hg))
		}
	}
	if cc := g.resolveServiceCheckCmd(h.CheckCommand); cc != "" {
		buf.WriteString(cmdField("check_command", cc))
	}
	if h.UseTemplate != 0 {
		if tpl := g.resolveHostTemplate(h.ID); tpl != "" {
			buf.WriteString(cmdField("use", tpl))
		}
	}
	if h.MaxCheckAttempts != nil {
		buf.WriteString(cmdField("max_check_attempts", fmt.Sprint(*h.MaxCheckAttempts)))
	}
	if h.CheckInterval != nil {
		buf.WriteString(cmdField("check_interval", fmt.Sprint(*h.CheckInterval)))
	}
	if h.RetryInterval != nil {
		buf.WriteString(cmdField("retry_interval", fmt.Sprint(*h.RetryInterval)))
	}
	if h.ActiveChecksEnabled != 2 {
		buf.WriteString(cmdField("active_checks_enabled", fmt.Sprint(h.ActiveChecksEnabled)))
	}
	if h.PassiveChecksEnabled != 2 {
		buf.WriteString(cmdField("passive_checks_enabled", fmt.Sprint(h.PassiveChecksEnabled)))
	}
	if p := g.resolveTimeperiodName(h.CheckPeriod); p != "" {
		buf.WriteString(cmdField("check_period", p))
	}
	if h.ObsessOverHost != 2 {
		buf.WriteString(cmdField("obsess_over_host", fmt.Sprint(h.ObsessOverHost)))
	}
	if h.CheckFreshness != 2 {
		buf.WriteString(cmdField("check_freshness", fmt.Sprint(h.CheckFreshness)))
	}
	if h.EventHandlerEnabled != 2 {
		buf.WriteString(cmdField("event_handler_enabled", fmt.Sprint(h.EventHandlerEnabled)))
	}
	if h.FlapDetectionEnabled != 2 {
		buf.WriteString(cmdField("flap_detection_enabled", fmt.Sprint(h.FlapDetectionEnabled)))
	}
	if h.ProcessPerfData != 2 {
		buf.WriteString(cmdField("process_perf_data", fmt.Sprint(h.ProcessPerfData)))
	}
	if h.RetainStatusInfo != 2 {
		buf.WriteString(cmdField("retain_status_information", fmt.Sprint(h.RetainStatusInfo)))
	}
	if h.RetainNonstatusInfo != 2 {
		buf.WriteString(cmdField("retain_nonstatus_information", fmt.Sprint(h.RetainNonstatusInfo)))
	}
	if h.ContactGroups != 0 {
		if cg := g.resolveHostContactgroups(h.ID); cg != "" {
			buf.WriteString(cmdField("contact_groups", cg))
		}
	}
	if h.NotificationInterval != nil {
		buf.WriteString(cmdField("notification_interval", fmt.Sprint(*h.NotificationInterval)))
	}
	if p := g.resolveTimeperiodName(h.NotificationPeriod); p != "" {
		buf.WriteString(cmdField("notification_period", p))
	}
	if h.NotificationOptions != "" {
		buf.WriteString(cmdField("notification_options", h.NotificationOptions))
	}
	if h.NotificationsEnabled != 2 {
		buf.WriteString(cmdField("notifications_enabled", fmt.Sprint(h.NotificationsEnabled)))
	}
	if h.Notes != "" {
		buf.WriteString(cmdField("notes", h.Notes))
	}
	buf.WriteString(cmdField("register", h.Register))
	buf.WriteString("}\t\n\n")
	return buf.Bytes(), nil
}

func (g *Generator) renderService(s *models.Service) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("define service {\n")

	// Fields follow DB column order of tbl_service (PHP uses SELECT * → foreach).
	buf.WriteString(cmdField("#NAGIOSQL_CONFIG_NAME", s.ConfigName))
	if hosts := g.resolveServiceHosts(s.ID); hosts != "" {
		buf.WriteString(cmdField("host_name", hosts))
	}
	buf.WriteString(cmdField("service_description", s.ServiceDescription))
	if s.DisplayName != "" {
		buf.WriteString(cmdField("display_name", s.DisplayName))
	}
	if s.UseTemplate != 0 {
		if tpl := g.resolveServiceTemplate(s.ID); tpl != "" {
			buf.WriteString(cmdField("use", tpl))
		}
	}
	if cc := g.resolveServiceCheckCmd(s.CheckCommand); cc != "" {
		buf.WriteString(cmdField("check_command", cc))
	}
	if s.IsVolatile != 2 {
		buf.WriteString(cmdField("is_volatile", fmt.Sprint(s.IsVolatile)))
	}
	if s.MaxCheckAttempts != nil {
		buf.WriteString(cmdField("max_check_attempts", fmt.Sprint(*s.MaxCheckAttempts)))
	}
	if s.CheckInterval != nil {
		buf.WriteString(cmdField("check_interval", fmt.Sprint(*s.CheckInterval)))
	}
	if s.RetryInterval != nil {
		buf.WriteString(cmdField("retry_interval", fmt.Sprint(*s.RetryInterval)))
	}
	if s.ActiveChecksEnabled != 2 {
		buf.WriteString(cmdField("active_checks_enabled", fmt.Sprint(s.ActiveChecksEnabled)))
	}
	if s.PassiveChecksEnabled != 2 {
		buf.WriteString(cmdField("passive_checks_enabled", fmt.Sprint(s.PassiveChecksEnabled)))
	}
	if p := g.resolveTimeperiodName(s.CheckPeriod); p != "" {
		buf.WriteString(cmdField("check_period", p))
	}
	if s.ParallelizeCheck != 2 {
		buf.WriteString(cmdField("parallelize_check", fmt.Sprint(s.ParallelizeCheck)))
	}
	if s.ObsessOverService != 2 {
		buf.WriteString(cmdField("obsess_over_service", fmt.Sprint(s.ObsessOverService)))
	}
	if s.CheckFreshness != 2 {
		buf.WriteString(cmdField("check_freshness", fmt.Sprint(s.CheckFreshness)))
	}
	if s.EventHandlerEnabled != 2 {
		buf.WriteString(cmdField("event_handler_enabled", fmt.Sprint(s.EventHandlerEnabled)))
	}
	if s.FlapDetectionEnabled != 2 {
		buf.WriteString(cmdField("flap_detection_enabled", fmt.Sprint(s.FlapDetectionEnabled)))
	}
	if s.ProcessPerfData != 2 {
		buf.WriteString(cmdField("process_perf_data", fmt.Sprint(s.ProcessPerfData)))
	}
	if s.RetainStatusInfo != 2 {
		buf.WriteString(cmdField("retain_status_information", fmt.Sprint(s.RetainStatusInfo)))
	}
	if s.RetainNonstatusInfo != 2 {
		buf.WriteString(cmdField("retain_nonstatus_information", fmt.Sprint(s.RetainNonstatusInfo)))
	}
	if s.NotificationInterval != nil {
		buf.WriteString(cmdField("notification_interval", fmt.Sprint(*s.NotificationInterval)))
	}
	if p := g.resolveTimeperiodName(s.NotificationPeriod); p != "" {
		buf.WriteString(cmdField("notification_period", p))
	}
	if s.NotificationOptions != "" {
		buf.WriteString(cmdField("notification_options", s.NotificationOptions))
	}
	if s.NotificationsEnabled != 2 {
		buf.WriteString(cmdField("notifications_enabled", fmt.Sprint(s.NotificationsEnabled)))
	}
	if s.ContactGroups != 0 {
		if cg := g.resolveServiceContactgroups(s.ID); cg != "" {
			buf.WriteString(cmdField("contact_groups", cg))
		}
	}
	if s.Notes != "" {
		buf.WriteString(cmdField("notes", s.Notes))
	}
	buf.WriteString(cmdField("register", s.Register))
	buf.WriteString("}\t\n")
	return buf.Bytes(), nil
}

// --- FK resolvers ---

func (g *Generator) resolveHostTemplate(hostID uint) string {
	var name string
	g.db.Raw(`SELECT t.template_name FROM tbl_hosttemplate t
		INNER JOIN tbl_lnkHostToHosttemplate l ON l.idSlave = t.id
		WHERE l.idMaster = ? ORDER BY l.idSort LIMIT 1`, hostID).Scan(&name)
	return name
}

func (g *Generator) resolveServiceTemplate(serviceID uint) string {
	var name string
	g.db.Raw(`SELECT t.template_name FROM tbl_servicetemplate t
		INNER JOIN tbl_lnkServiceToServicetemplate l ON l.idSlave = t.id
		WHERE l.idMaster = ? ORDER BY l.idSort LIMIT 1`, serviceID).Scan(&name)
	return name
}

func (g *Generator) resolveHostContactgroups(hostID uint) string {
	var names []string
	// tbl_lnkHostToContactgroup has no idSort column — order by name for stability.
	g.db.Raw(`SELECT c.contactgroup_name FROM tbl_contactgroup c
		INNER JOIN tbl_lnkHostToContactgroup l ON l.idSlave = c.id
		WHERE l.idMaster = ? ORDER BY c.contactgroup_name`, hostID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveServiceContactgroups(serviceID uint) string {
	var names []string
	g.db.Raw(`SELECT c.contactgroup_name FROM tbl_contactgroup c
		INNER JOIN tbl_lnkServiceToContactgroup l ON l.idSlave = c.id
		WHERE l.idMaster = ? ORDER BY c.contactgroup_name`, serviceID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveServiceHosts(serviceID uint) string {
	var names []string
	// tbl_lnkServiceToHost has no idSort column — order by host_name for stability.
	g.db.Raw(`SELECT h.host_name FROM tbl_host h
		INNER JOIN tbl_lnkServiceToHost l ON l.idSlave = h.id
		WHERE l.idMaster = ? ORDER BY h.host_name`, serviceID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveContactgroupMembers(cgID uint) string {
	var names []string
	g.db.Raw(`SELECT c.contact_name FROM tbl_contact c
		INNER JOIN tbl_lnkContactgroupToContact l ON l.idSlave = c.id
		WHERE l.idMaster = ? ORDER BY c.contact_name`, cgID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveContactTemplate(contactID uint) string {
	var name string
	g.db.Raw(`SELECT t.template_name FROM tbl_contacttemplate t
		INNER JOIN tbl_lnkContactToContacttemplate l ON l.idSlave = t.id
		WHERE l.idMaster = ? LIMIT 1`, contactID).Scan(&name)
	return name
}

func (g *Generator) resolveContactTemplateHostCmd(ctID uint) string {
	var name string
	g.db.Raw(`SELECT c.command_name FROM tbl_command c
		INNER JOIN tbl_lnkContacttemplateToCommandHost l ON l.idSlave = c.id
		WHERE l.idMaster = ? LIMIT 1`, ctID).Scan(&name)
	return name
}

func (g *Generator) resolveContactTemplateSvcCmd(ctID uint) string {
	var name string
	g.db.Raw(`SELECT c.command_name FROM tbl_command c
		INNER JOIN tbl_lnkContacttemplateToCommandService l ON l.idSlave = c.id
		WHERE l.idMaster = ? LIMIT 1`, ctID).Scan(&name)
	return name
}

func (g *Generator) resolveTimeperiodName(tpID uint) string {
	if tpID == 0 {
		return ""
	}
	var name string
	g.db.Raw(`SELECT timeperiod_name FROM tbl_timeperiod WHERE id = ? LIMIT 1`, tpID).Scan(&name)
	return name
}

func (g *Generator) resolveHostgroupMembers(hgID uint) string {
	var names []string
	g.db.Raw(`SELECT h.host_name FROM tbl_host h
		INNER JOIN tbl_lnkHostgroupToHost l ON l.idSlave = h.id
		WHERE l.idMaster = ? ORDER BY h.host_name`, hgID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveHostHostgroups(hostID uint) string {
	var names []string
	g.db.Raw(`SELECT h.hostgroup_name FROM tbl_hostgroup h
		INNER JOIN tbl_lnkHostToHostgroup l ON l.idSlave = h.id
		WHERE l.idMaster = ? ORDER BY h.hostgroup_name`, hostID).Scan(&names)
	return strings.Join(names, ",")
}

// resolveServiceCheckCmd resolves a check_command value stored as "<id>::bang::<args>"
// or "<id>!<args>" into "<command_name>!<args>".
func (g *Generator) resolveServiceCheckCmd(raw string) string {
	if raw == "" || raw == "0" {
		return ""
	}
	decoded := bangDecode(raw)
	parts := strings.SplitN(decoded, "!", 2)
	id, err := strconv.Atoi(strings.TrimSpace(parts[0]))
	if err != nil || id == 0 {
		return decoded
	}
	var name string
	g.db.Raw(`SELECT command_name FROM tbl_command WHERE id = ? LIMIT 1`, id).Scan(&name)
	if name == "" {
		return decoded
	}
	if len(parts) == 2 && parts[1] != "" {
		return name + "!" + parts[1]
	}
	return name
}

func (g *Generator) resolveHostTemplateParent(htID uint) string {
	var name string
	g.db.Raw(`SELECT t.template_name FROM tbl_hosttemplate t
		INNER JOIN tbl_lnkHosttemplateToHosttemplate l ON l.idSlave = t.id
		WHERE l.idMaster = ? ORDER BY l.idSort LIMIT 1`, htID).Scan(&name)
	return name
}

func (g *Generator) resolveHostTemplateHostgroups(htID uint) string {
	var names []string
	g.db.Raw(`SELECT h.hostgroup_name FROM tbl_hostgroup h
		INNER JOIN tbl_lnkHosttemplateToHostgroup l ON l.idSlave = h.id
		WHERE l.idMaster = ? ORDER BY h.hostgroup_name`, htID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveHostTemplateContactGroups(htID uint) string {
	var names []string
	g.db.Raw(`SELECT c.contactgroup_name FROM tbl_contactgroup c
		INNER JOIN tbl_lnkHosttemplateToContactgroup l ON l.idSlave = c.id
		WHERE l.idMaster = ? ORDER BY c.contactgroup_name`, htID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveServiceTemplateParent(stID uint) string {
	var name string
	g.db.Raw(`SELECT t.template_name FROM tbl_servicetemplate t
		INNER JOIN tbl_lnkServicetemplateToServicetemplate l ON l.idSlave = t.id
		WHERE l.idMaster = ? ORDER BY l.idSort LIMIT 1`, stID).Scan(&name)
	return name
}

func (g *Generator) resolveServiceTemplateContactGroups(stID uint) string {
	var names []string
	g.db.Raw(`SELECT c.contactgroup_name FROM tbl_contactgroup c
		INNER JOIN tbl_lnkServicetemplateToContactgroup l ON l.idSlave = c.id
		WHERE l.idMaster = ? ORDER BY c.contactgroup_name`, stID).Scan(&names)
	return strings.Join(names, ",")
}

func (g *Generator) resolveTimeperiodUse(tpID uint) string {
	var name string
	g.db.Raw(`SELECT t.timeperiod_name FROM tbl_timeperiod t
		INNER JOIN tbl_lnkTimeperiodToTimeperiodUse l ON l.idSlave = t.id
		WHERE l.idMaster = ? LIMIT 1`, tpID).Scan(&name)
	return name
}

func (g *Generator) resolveTimedefinitions(tpID uint) [][2]string {
	type row struct {
		Definition string
		Range      string
	}
	var rows []row
	// No ORDER BY — matches PHP behavior (SELECT without ORDER BY returns storage order).
	g.db.Raw(`SELECT definition, `+"`range`"+` FROM tbl_timedefinition
		WHERE tipId = ?`, tpID).Scan(&rows)
	out := make([][2]string, len(rows))
	for i, r := range rows {
		out[i] = [2]string{r.Definition, r.Range}
	}
	return out
}

// resolveCommandIDStr resolves a check_command field that is stored as a numeric
// command ID in tbl_hosttemplate/tbl_servicetemplate. Returns "" if 0 or unset.
func (g *Generator) resolveCommandIDStr(idStr string) string {
	if idStr == "" || idStr == "0" {
		return ""
	}
	id, err := strconv.Atoi(strings.TrimSpace(idStr))
	if err != nil || id == 0 {
		return bangDecode(idStr)
	}
	var name string
	g.db.Raw(`SELECT command_name FROM tbl_command WHERE id = ? LIMIT 1`, id).Scan(&name)
	return name
}

// --- Formatting helpers ---

// cmdField formats a key=value pair matching PHP NagiosQL commands.cfg output:
// TAB indent, key padded to 31 chars, TAB separator, then value.
func cmdField(key, value string) string {
	pad := max(1, 31-len(key))
	return "\t" + key + strings.Repeat(" ", pad) + "\t" + value + "\n"
}

// bangDecode converts NagiosQL's internal bang-escape back to the '!'
// separator that Nagios uses for command arguments.
func bangDecode(s string) string {
	s = strings.ReplaceAll(s, `\::bang::`, "!")
	s = strings.ReplaceAll(s, "::bang::", "!")
	return s
}

// sanitizeName removes characters unsafe for filenames.
func sanitizeName(name string) string {
	r := strings.NewReplacer("/", "_", "\\", "_", ":", "_", " ", "_")
	return r.Replace(name)
}

// --- Generic FK resolvers ---

// resolveN2N resolves an n:n FK relationship (relation type=2) by joining through a link table.
// It returns a comma-separated list of targetField values from targetTable for all active records
// linked to masterID in linkTable.
func (g *Generator) resolveN2N(masterID uint, linkTable, targetTable, targetField string) string {
	names := []string{}
	q := `SELECT t.` + targetField + ` FROM ` + targetTable + ` t` +
		` INNER JOIN ` + linkTable + ` l ON l.idSlave = t.id` +
		` WHERE l.idMaster = ? AND t.active = '1' ORDER BY t.` + targetField
	g.db.Raw(q, masterID).Scan(&names)
	return strings.Join(names, ",")
}

// resolveStrSlave resolves a type=6 FK where the value is stored directly as the strSlave string
// column in the link table (used for service_description fields). Returns a comma-separated list.
func (g *Generator) resolveStrSlave(masterID uint, linkTable string) string {
	names := []string{}
	g.db.Raw(`SELECT strSlave FROM `+linkTable+` WHERE idMaster = ? ORDER BY strSlave`, masterID).Scan(&names)
	return strings.Join(names, ",")
}

// resolveHostByID resolves a direct host FK (type=1) by looking up host_name in tbl_host by id.
// Returns an empty string when id is 0 or the record is not found.
func (g *Generator) resolveHostByID(id uint) string {
	if id == 0 {
		return ""
	}
	var name string
	g.db.Raw(`SELECT host_name FROM tbl_host WHERE id = ? LIMIT 1`, id).Scan(&name)
	return name
}

// resolveServiceByID resolves a direct service FK (type=1) by looking up service_description in
// tbl_service by id. Returns an empty string when id is 0 or the record is not found.
func (g *Generator) resolveServiceByID(id uint) string {
	if id == 0 {
		return ""
	}
	var name string
	g.db.Raw(`SELECT service_description FROM tbl_service WHERE id = ? LIMIT 1`, id).Scan(&name)
	return name
}

// resolveServicegroupMembers resolves type=5 servicegroup members for the given sgID.
// Each row in tbl_lnkServicegroupToService can reference either a direct host (idSlaveH) or a
// hostgroup (idSlaveHG) combined with a service (idSlaveS). Hostgroup references are expanded to
// individual host+service pairs by querying both link directions. Excluded rows are skipped.
// Returns a flat comma-separated "host,svc,host,svc,..." string as required by Nagios.
func (g *Generator) resolveServicegroupMembers(sgID uint) string {
	type row struct {
		SlaveH  uint  `gorm:"column:idSlaveH"`
		SlaveHG uint  `gorm:"column:idSlaveHG"`
		SlaveS  uint  `gorm:"column:idSlaveS"`
		Exclude uint8 `gorm:"column:exclude"`
	}
	var rows []row
	g.db.Raw(`SELECT idSlaveH, idSlaveHG, idSlaveS, exclude FROM tbl_lnkServicegroupToService WHERE idMaster = ?`, sgID).Scan(&rows)

	parts := []string{}
	seen := map[string]bool{}
	for _, r := range rows {
		if r.Exclude != 0 {
			continue
		}
		if r.SlaveHG != 0 {
			var svcDesc string
			g.db.Raw(`SELECT service_description FROM tbl_service WHERE id = ? LIMIT 1`, r.SlaveS).Scan(&svcDesc)
			var hosts []string
			g.db.Raw(`SELECT h.host_name FROM tbl_host h
				INNER JOIN tbl_lnkHostgroupToHost l ON l.idSlave = h.id
				WHERE l.idMaster = ? AND h.active = '1' AND l.exclude = 0`, r.SlaveHG).Scan(&hosts)
			var hosts2 []string
			g.db.Raw(`SELECT h.host_name FROM tbl_host h
				INNER JOIN tbl_lnkHostToHostgroup l ON l.idMaster = h.id
				WHERE l.idSlave = ? AND h.active = '1' AND l.exclude = 0`, r.SlaveHG).Scan(&hosts2)
			hosts = append(hosts, hosts2...)
			for _, h := range hosts {
				key := h + "," + svcDesc
				if !seen[key] {
					seen[key] = true
					parts = append(parts, key)
				}
			}
		} else {
			var hostName, svcDesc string
			g.db.Raw(`SELECT host_name FROM tbl_host WHERE id = ? AND active = '1' LIMIT 1`, r.SlaveH).Scan(&hostName)
			g.db.Raw(`SELECT service_description FROM tbl_service WHERE id = ? AND active = '1' LIMIT 1`, r.SlaveS).Scan(&svcDesc)
			if hostName != "" && svcDesc != "" {
				parts = append(parts, hostName+","+svcDesc)
			}
		}
	}
	return strings.Join(parts, ",")
}

// --- Writers for the 7 extended object types ---

// WriteServiceGroups generates the Nagios servicegroup configuration file from all active
// tbl_servicegroup records and writes it (with backup) to outputFile.
func (g *Generator) WriteServiceGroups(outputFile string) error {
	var rows []models.Servicegroup
	if err := g.db.Where("active = '1'").Order("servicegroup_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading servicegroups: %w", err)
	}
	var buf bytes.Buffer
	for _, sg := range rows {
		buf.WriteString("define servicegroup {\n")
		buf.WriteString(cmdField("servicegroup_name", sg.ServicegroupName))
		buf.WriteString(cmdField("alias", sg.Alias))
		if sg.Members != 0 {
			if m := g.resolveServicegroupMembers(sg.ID); m != "" {
				buf.WriteString(cmdField("members", m))
			}
		}
		if sg.ServicegroupMembers != 0 {
			if m := g.resolveN2N(sg.ID, "tbl_lnkServicegroupToServicegroup", "tbl_servicegroup", "servicegroup_name"); m != "" {
				buf.WriteString(cmdField("servicegroup_members", m))
			}
		}
		if sg.Notes != "" {
			buf.WriteString(cmdField("notes", sg.Notes))
		}
		if sg.NotesURL != "" {
			buf.WriteString(cmdField("notes_url", sg.NotesURL))
		}
		if sg.ActionURL != "" {
			buf.WriteString(cmdField("action_url", sg.ActionURL))
		}
		buf.WriteString(cmdField("register", sg.Register))
		buf.WriteString("}\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Service group configuration file", buf.Bytes()))
}

// WriteHostDependencies generates the Nagios hostdependency configuration file from all active
// tbl_hostdependency records and writes it (with backup) to outputFile.
func (g *Generator) WriteHostDependencies(outputFile string) error {
	var rows []models.Hostdependency
	if err := g.db.Where("active = '1'").Order("dependent_host_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading hostdependencies: %w", err)
	}
	var buf bytes.Buffer
	for _, hd := range rows {
		buf.WriteString("define hostdependency {\n")
		if hd.ConfigName != "" {
			buf.WriteString(cmdField("#NAGIOSQL_CONFIG_NAME", hd.ConfigName))
		}
		if hd.DependentHostName != 0 {
			if v := g.resolveN2N(hd.ID, "tbl_lnkHostdependencyToHost_DH", "tbl_host", "host_name"); v != "" {
				buf.WriteString(cmdField("dependent_host_name", v))
			}
		}
		if hd.DependentHostgroupName != 0 {
			if v := g.resolveN2N(hd.ID, "tbl_lnkHostdependencyToHostgroup_DH", "tbl_hostgroup", "hostgroup_name"); v != "" {
				buf.WriteString(cmdField("dependent_hostgroup_name", v))
			}
		}
		if hd.HostName != 0 {
			if v := g.resolveN2N(hd.ID, "tbl_lnkHostdependencyToHost_H", "tbl_host", "host_name"); v != "" {
				buf.WriteString(cmdField("host_name", v))
			}
		}
		if hd.HostgroupName != 0 {
			if v := g.resolveN2N(hd.ID, "tbl_lnkHostdependencyToHostgroup_H", "tbl_hostgroup", "hostgroup_name"); v != "" {
				buf.WriteString(cmdField("hostgroup_name", v))
			}
		}
		buf.WriteString(cmdField("inherits_parent", fmt.Sprintf("%d", hd.InheritsParent)))
		if hd.ExecutionFailureCriteria != "" {
			buf.WriteString(cmdField("execution_failure_criteria", hd.ExecutionFailureCriteria))
		}
		if hd.NotificationFailureCriteria != "" {
			buf.WriteString(cmdField("notification_failure_criteria", hd.NotificationFailureCriteria))
		}
		if tp := g.resolveTimeperiodName(hd.DependencyPeriod); tp != "" {
			buf.WriteString(cmdField("dependency_period", tp))
		}
		buf.WriteString(cmdField("register", hd.Register))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Host dependency configuration file", buf.Bytes()))
}

// WriteHostEscalations generates the Nagios hostescalation configuration file from all active
// tbl_hostescalation records and writes it (with backup) to outputFile.
func (g *Generator) WriteHostEscalations(outputFile string) error {
	var rows []models.Hostescalation
	if err := g.db.Where("active = '1'").Order("host_name, hostgroup_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading hostescalations: %w", err)
	}
	var buf bytes.Buffer
	for _, he := range rows {
		buf.WriteString("define hostescalation {\n")
		if he.ConfigName != "" {
			buf.WriteString(cmdField("#NAGIOSQL_CONFIG_NAME", he.ConfigName))
		}
		if he.HostName != 0 {
			if v := g.resolveN2N(he.ID, "tbl_lnkHostescalationToHost", "tbl_host", "host_name"); v != "" {
				buf.WriteString(cmdField("host_name", v))
			}
		}
		if he.HostgroupName != 0 {
			if v := g.resolveN2N(he.ID, "tbl_lnkHostescalationToHostgroup", "tbl_hostgroup", "hostgroup_name"); v != "" {
				buf.WriteString(cmdField("hostgroup_name", v))
			}
		}
		if he.Contacts != 0 {
			if v := g.resolveN2N(he.ID, "tbl_lnkHostescalationToContact", "tbl_contact", "contact_name"); v != "" {
				buf.WriteString(cmdField("contacts", v))
			}
		}
		if he.ContactGroups != 0 {
			if v := g.resolveN2N(he.ID, "tbl_lnkHostescalationToContactgroup", "tbl_contactgroup", "contactgroup_name"); v != "" {
				buf.WriteString(cmdField("contact_groups", v))
			}
		}
		if he.FirstNotification != nil {
			buf.WriteString(cmdField("first_notification", fmt.Sprintf("%d", *he.FirstNotification)))
		}
		if he.LastNotification != nil {
			buf.WriteString(cmdField("last_notification", fmt.Sprintf("%d", *he.LastNotification)))
		}
		if he.NotificationInterval != nil {
			buf.WriteString(cmdField("notification_interval", fmt.Sprintf("%d", *he.NotificationInterval)))
		}
		if tp := g.resolveTimeperiodName(he.EscalationPeriod); tp != "" {
			buf.WriteString(cmdField("escalation_period", tp))
		}
		if he.EscalationOptions != "" {
			buf.WriteString(cmdField("escalation_options", he.EscalationOptions))
		}
		buf.WriteString(cmdField("register", he.Register))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Host escalations configuration file", buf.Bytes()))
}

// WriteHostExtInfo generates the Nagios extended host information configuration file from all active
// tbl_hostextinfo records and writes it (with backup) to outputFile.
func (g *Generator) WriteHostExtInfo(outputFile string) error {
	var rows []models.Hostextinfo
	if err := g.db.Where("active = '1'").Order("host_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading hostextinfo: %w", err)
	}
	var buf bytes.Buffer
	for _, hi := range rows {
		buf.WriteString("define hostextinfo {\n")
		if v := g.resolveHostByID(hi.HostName); v != "" {
			buf.WriteString(cmdField("host_name", v))
		}
		if hi.Notes != "" {
			buf.WriteString(cmdField("notes", hi.Notes))
		}
		if hi.NotesURL != "" {
			buf.WriteString(cmdField("notes_url", hi.NotesURL))
		}
		if hi.ActionURL != "" {
			buf.WriteString(cmdField("action_url", hi.ActionURL))
		}
		if hi.IconImage != "" {
			buf.WriteString(cmdField("icon_image", hi.IconImage))
		}
		if hi.IconImageAlt != "" {
			buf.WriteString(cmdField("icon_image_alt", hi.IconImageAlt))
		}
		if hi.VrmlImage != "" {
			buf.WriteString(cmdField("vrml_image", hi.VrmlImage))
		}
		if hi.StatusmapImage != "" {
			buf.WriteString(cmdField("statusmap_image", hi.StatusmapImage))
		}
		if hi.Coords2D != "" {
			buf.WriteString(cmdField("2d_coords", hi.Coords2D))
		}
		if hi.Coords3D != "" {
			buf.WriteString(cmdField("3d_coords", hi.Coords3D))
		}
		buf.WriteString(cmdField("register", hi.Register))
		buf.WriteString("}\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Extended host information configuration file", buf.Bytes()))
}

// WriteServiceDependencies generates the Nagios servicedependency configuration file from all active
// tbl_servicedependency records and writes it (with backup) to outputFile.
func (g *Generator) WriteServiceDependencies(outputFile string) error {
	var rows []models.Servicedependency
	if err := g.db.Where("active = '1'").Order("config_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading servicedependencies: %w", err)
	}
	var buf bytes.Buffer
	for _, sd := range rows {
		buf.WriteString("define servicedependency {\n")
		if sd.ConfigName != "" {
			buf.WriteString(cmdField("#NAGIOSQL_CONFIG_NAME", sd.ConfigName))
		}
		if sd.DependentHostName != 0 {
			if v := g.resolveN2N(sd.ID, "tbl_lnkServicedependencyToHost_DH", "tbl_host", "host_name"); v != "" {
				buf.WriteString(cmdField("dependent_host_name", v))
			}
		}
		if sd.DependentHostgroupName != 0 {
			if v := g.resolveN2N(sd.ID, "tbl_lnkServicedependencyToHostgroup_DH", "tbl_hostgroup", "hostgroup_name"); v != "" {
				buf.WriteString(cmdField("dependent_hostgroup_name", v))
			}
		}
		if sd.DependentServiceDescription != 0 {
			if v := g.resolveStrSlave(sd.ID, "tbl_lnkServicedependencyToService_DS"); v != "" {
				buf.WriteString(cmdField("dependent_service_description", v))
			}
		}
		if sd.DependentServicegroupName != 0 {
			if v := g.resolveN2N(sd.ID, "tbl_lnkServicedependencyToServicegroup_DS", "tbl_servicegroup", "servicegroup_name"); v != "" {
				buf.WriteString(cmdField("dependent_servicegroup_name", v))
			}
		}
		if sd.HostName != 0 {
			if v := g.resolveN2N(sd.ID, "tbl_lnkServicedependencyToHost_H", "tbl_host", "host_name"); v != "" {
				buf.WriteString(cmdField("host_name", v))
			}
		}
		if sd.HostgroupName != 0 {
			if v := g.resolveN2N(sd.ID, "tbl_lnkServicedependencyToHostgroup_H", "tbl_hostgroup", "hostgroup_name"); v != "" {
				buf.WriteString(cmdField("hostgroup_name", v))
			}
		}
		if sd.ServiceDescription != 0 {
			if v := g.resolveStrSlave(sd.ID, "tbl_lnkServicedependencyToService_S"); v != "" {
				buf.WriteString(cmdField("service_description", v))
			}
		}
		if sd.ServicegroupName != 0 {
			if v := g.resolveN2N(sd.ID, "tbl_lnkServicedependencyToServicegroup_S", "tbl_servicegroup", "servicegroup_name"); v != "" {
				buf.WriteString(cmdField("servicegroup_name", v))
			}
		}
		buf.WriteString(cmdField("inherits_parent", fmt.Sprintf("%d", sd.InheritsParent)))
		if sd.ExecutionFailureCriteria != "" {
			buf.WriteString(cmdField("execution_failure_criteria", sd.ExecutionFailureCriteria))
		}
		if sd.NotificationFailureCriteria != "" {
			buf.WriteString(cmdField("notification_failure_criteria", sd.NotificationFailureCriteria))
		}
		if tp := g.resolveTimeperiodName(sd.DependencyPeriod); tp != "" {
			buf.WriteString(cmdField("dependency_period", tp))
		}
		buf.WriteString(cmdField("register", sd.Register))
		buf.WriteString("}\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Service dependency configuration file", buf.Bytes()))
}

// WriteServiceEscalations generates the Nagios serviceescalation configuration file from all active
// tbl_serviceescalation records and writes it (with backup) to outputFile.
func (g *Generator) WriteServiceEscalations(outputFile string) error {
	var rows []models.Serviceescalation
	if err := g.db.Where("active = '1'").Order("config_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading serviceescalations: %w", err)
	}
	var buf bytes.Buffer
	for _, se := range rows {
		buf.WriteString("define serviceescalation {\n")
		if se.ConfigName != "" {
			buf.WriteString(cmdField("#NAGIOSQL_CONFIG_NAME", se.ConfigName))
		}
		if se.HostName != 0 {
			if v := g.resolveN2N(se.ID, "tbl_lnkServiceescalationToHost", "tbl_host", "host_name"); v != "" {
				buf.WriteString(cmdField("host_name", v))
			}
		}
		if se.HostgroupName != 0 {
			if v := g.resolveN2N(se.ID, "tbl_lnkServiceescalationToHostgroup", "tbl_hostgroup", "hostgroup_name"); v != "" {
				buf.WriteString(cmdField("hostgroup_name", v))
			}
		}
		if se.ServiceDescription != 0 {
			if v := g.resolveStrSlave(se.ID, "tbl_lnkServiceescalationToService"); v != "" {
				buf.WriteString(cmdField("service_description", v))
			}
		}
		if se.ServicegroupName != 0 {
			if v := g.resolveN2N(se.ID, "tbl_lnkServiceescalationToServicegroup", "tbl_servicegroup", "servicegroup_name"); v != "" {
				buf.WriteString(cmdField("servicegroup_name", v))
			}
		}
		if se.Contacts != 0 {
			if v := g.resolveN2N(se.ID, "tbl_lnkServiceescalationToContact", "tbl_contact", "contact_name"); v != "" {
				buf.WriteString(cmdField("contacts", v))
			}
		}
		if se.ContactGroups != 0 {
			if v := g.resolveN2N(se.ID, "tbl_lnkServiceescalationToContactgroup", "tbl_contactgroup", "contactgroup_name"); v != "" {
				buf.WriteString(cmdField("contact_groups", v))
			}
		}
		if se.FirstNotification != nil {
			buf.WriteString(cmdField("first_notification", fmt.Sprintf("%d", *se.FirstNotification)))
		}
		if se.LastNotification != nil {
			buf.WriteString(cmdField("last_notification", fmt.Sprintf("%d", *se.LastNotification)))
		}
		if se.NotificationInterval != nil {
			buf.WriteString(cmdField("notification_interval", fmt.Sprintf("%d", *se.NotificationInterval)))
		}
		if tp := g.resolveTimeperiodName(se.EscalationPeriod); tp != "" {
			buf.WriteString(cmdField("escalation_period", tp))
		}
		if se.EscalationOptions != "" {
			buf.WriteString(cmdField("escalation_options", se.EscalationOptions))
		}
		buf.WriteString(cmdField("register", se.Register))
		buf.WriteString("}\t\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Service escalations configuration file", buf.Bytes()))
}

// WriteServiceExtInfo generates the Nagios extended service information configuration file from all
// active tbl_serviceextinfo records and writes it (with backup) to outputFile.
func (g *Generator) WriteServiceExtInfo(outputFile string) error {
	var rows []models.Serviceextinfo
	if err := g.db.Where("active = '1'").Order("host_name").Find(&rows).Error; err != nil {
		return fmt.Errorf("loading serviceextinfo: %w", err)
	}
	var buf bytes.Buffer
	for _, si := range rows {
		buf.WriteString("define serviceextinfo {\n")
		if v := g.resolveHostByID(si.HostName); v != "" {
			buf.WriteString(cmdField("host_name", v))
		}
		if v := g.resolveServiceByID(si.ServiceDescription); v != "" {
			buf.WriteString(cmdField("service_description", v))
		}
		if si.Notes != "" {
			buf.WriteString(cmdField("notes", si.Notes))
		}
		if si.NotesURL != "" {
			buf.WriteString(cmdField("notes_url", si.NotesURL))
		}
		if si.ActionURL != "" {
			buf.WriteString(cmdField("action_url", si.ActionURL))
		}
		if si.IconImage != "" {
			buf.WriteString(cmdField("icon_image", si.IconImage))
		}
		if si.IconImageAlt != "" {
			buf.WriteString(cmdField("icon_image_alt", si.IconImageAlt))
		}
		buf.WriteString(cmdField("register", si.Register))
		buf.WriteString("}\n\n")
	}
	return g.writeWithBackup(outputFile,
		g.wrapFile("Extended service information configuration file", buf.Bytes()))
}

// writeWithBackup copies the existing file to backup/ then overwrites it.
func (g *Generator) writeWithBackup(path string, content []byte) error {
	if _, err := os.Stat(path); err == nil {
		if err := os.MkdirAll(g.backupDir, 0755); err == nil {
			ts := time.Now().Format("20060102_150405")
			bak := filepath.Join(g.backupDir, filepath.Base(path)+"."+ts+".bak")
			data, _ := os.ReadFile(path)
			_ = os.WriteFile(bak, data, 0644)
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", filepath.Dir(path), err)
	}
	return os.WriteFile(path, content, 0644)
}
